### ISSUE TITLE
Errors when trying to start Genie 

### ISSUE THREAD

**Issue by mbeltagy** [essenciary/Genie.jl#33] opened 2018-03-19 18:32 UTC
I just installed Genie by 

```julia
Pkg.clone("https://github.com/essenciary/Genie.jl")
```

When try start it, I get 

```julia
julia> using Genie
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: config not defined
Stacktrace:
 [1] is_dev() at /home/user/.julia/Genie/src/configuration.jl:41
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] _require(::Symbol) at ./loading.jl:490
 [5] require(::Symbol) at ./loading.jl:405
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] eval(::Module, ::Any) at ./boot.jl:235
 [8] _require(::Symbol) at ./loading.jl:490
 [9] require(::Symbol) at ./loading.jl:405
 [10] include_from_node1(::String) at ./loading.jl:576
 [11] include(::String) at ./sysimg.jl:14
 [12] include_from_node1(::String) at ./loading.jl:576
 [13] eval(::Module, ::Any) at ./boot.jl:235
 [14] _require(::Symbol) at ./loading.jl:490
 [15] require(::Symbol) at ./loading.jl:405
while loading /home/user/.julia/Genie/src/App.jl, in expression starting on line 8
while loading /home/user/.julia/Genie/src/Inflector.jl, in expression starting on line 6
while loading /home/user/.julia/Genie/src/file_templates.jl, in expression starting on line 6
while loading /home/user/.julia/Genie/src/Genie.jl, in expression starting on line 32
```
I am using 

```julia
julia> versioninfo()
Julia Version 0.6.3-pre.0
Commit 93168a6 (2017-12-18 07:11 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

```

**Comment by grandtiger** [comment] 2018-03-20 15:53
I ran into the same problem, on both Windows and Linux. A fix would be great. Thanks!

**Comment by mbeltagy** [comment] 2018-03-20 15:57
It is a single line fix.  See the pull request.  Hopefully,  it gets merged.

**Comment by essenciary** [comment] 2018-03-21 07:17
Thanks - I can't reproduce the error but I see no problem setting the default. Merged, thanks for your contribution!

**Closed by essenciary** 2018-03-21 07:17 UTC

**Comment by mbeltagy** [comment] 2018-03-21 07:19
Perhaps we need to set up testing and travis integration. I would be happy to help.

**Comment by essenciary** [comment] 2018-03-21 09:41
Yes, definitely! The framework is quite rich now in terms of features, so I'm putting more of my time into consolidation of other areas. Top priorities are: 
* user documentation - I'm working on a series of guides and tutorials for using Genie
* code documentation - planning on going over the docstrings, updating and rebuilding docs
* tests - adding extensive tests for the framework
* setting up CI (running tests, building docs, etc)
* registering the package

Help with any of these is greatly appreciated. However CI won't be useful unless there's a proper testing suite. And that is tricky - I've been thinking about it lately, in preparation for this. A lot of the functionality is about running requests through the web server, generating and loading files, etc - so a significant amount of integration testing. But of course, some things are better candidates for unit testing so that's a good start.

**Comment by precis19** [comment] 2022-05-15 17:36
Please what is the problem if search feature doesn't work Genie julia ?
